### ISSUE TITLE
can't build 0.2

### ISSUE THREAD

**Issue by igrigorik** [dcadenas/rankable_graph#1]
native extensions fails to build (64 bit, CentOS 5.2):

<pre>
gcc -I. -I/usr/local/include/ruby-1.9.1/x86_64-linux -I/usr/local/include/ruby-1.9.1/ruby/backward -I/usr/local/include/ruby-1.9.1 -I.   -fPIC -O3 -g -Wall -Wno-unused-parameter -Wno-parentheses -Wno-missing-field-initializers -Wpointer-arith -Wwrite-strings -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include    -o rankable_graph.o -c rankable_graph.c
rankable_graph.c: In function 'rankable_graph_allocate':
rankable_graph.c:27: warning: implicit declaration of function 'g_ptr_array_new_with_free_func'
rankable_graph.c:27: warning: assignment makes pointer from integer without a cast
rankable_graph.c:28: warning: assignment makes pointer from integer without a cast
rankable_graph.c: In function 'rank':
rankable_graph.c:171: warning: implicit declaration of function 'g_assert_cmpuint'
rankable_graph.c:171: error: expected expression before '==' token
rankable_graph.c:172: error: expected expression before '==' token
make: *** [rankable_graph.o] Error 1
</pre>

**Comment by ghost** [comment]
Are you using glib2 >= 2.22 ?

**Comment by igrigorik** [comment]
Hmm, ok, finally got glib2 port to build on my Mac. Haven't tried CentOS again yet, but you're probably right, my guess is that yum installed a lower version. Cheers!

**Comment by ghost** [comment]
Yay! and thanks a lot for your feedback!
